# Change these first
owner: italbanesi # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: COG 
    url: https://app.albanesi.com.ar/COG
    maxResponseTime: 5000
    __dangerous__body_down: "Imposible acceder a los datos"
  - name: CE 
    url: https://app.albanesi.com.ar/CE   
    maxResponseTime: 5000
    __dangerous__body_down: "Imposible acceder a los datos"
  - name: Gas
    url: https://app.albanesi.com.ar/Gas/assets/img/backgrounds/1.jpg
    maxResponseTime: 5000
  - name: API Cammesa / Conectividad local
    url: http://cogpub.albanesi.com.ar:8080/PUBAPI/API/ws.asmx/ExecuteTask?ID=F9AC1E99-6961-48FD-960D-2D098FA1FD57&Desde=2021-07-01T00:00:00&Hasta=2022-06-01T00:00:00
  - name: API Cammesa / Origen de datos
    url: https://api.cammesa.com/pub-svc/public/findDocumentosByNemoRango?fechadesde=2021-07-01T00:00:00&fechahasta=2021-07-01T00:00:00&nemo=PROGRAMACION_DIARIA
  - name: Publicador SOTR
    url: http://sotr.albanesi.com.ar/Desktop/DesktopLogin.aspx
    maxResponseTime: 5000
  # - name: GAS
  #   url: http://gas.albanesi.com.ar/login

assignees: # Users to assign downtime issues (optional)
  - ITAlbanesi

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: ocean
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Up Time Albanesi
  introTitle: "**APP STATUS**"
  introMessage: Esta página muestra información en **vivo** sobre el estado de las aplicaciones.
  navbar:
    - title: Status
      href: /uptime
   
workflowSchedule ggghik iij iiii
  <romper>, 
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"   

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
